#include "bundle_transport.h"

#include "driver/usb_serial_jtag.h"
#include "esp_heap_caps.h"
#include "esp_log.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "mbedtls/base64.h"
#include "mbedtls/sha256.h"

#include <inttypes.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static const char *TAG = "tsx_bundle_transport";

#define LINE_BUFFER_CAPACITY 512U
#define MANIFEST_BUFFER_CAPACITY 2048U
#define READ_CHUNK_BYTES 128U
#define READ_POLL_MS 50U
#define INACTIVITY_TIMEOUT_MS 2000U
#define RELOAD_TIMEOUT_MS 5000U
/* (DATA_CHUNK_BASE64_LIMIT / 4) * 3, mirrors packages/bundler/src/transport.ts. */
#define DATA_CHUNK_MAX_BYTES 288U

/*
 * TX/RX split: the USB Serial/JTAG *driver* (installed below) owns only the
 * RX ring buffer this task reads with `usb_serial_jtag_read_bytes`. Every
 * response frame goes out through `printf`/`ESP_LOG`, i.e. the existing
 * secondary-console path (`CONFIG_ESP_CONSOLE_SECONDARY_USB_SERIAL_JTAG`),
 * which writes the same physical port through its own low-level, driver-
 * independent path. That keeps `ESP_LOGx` output working unmodified and
 * avoids two writers contending for the driver's TX FIFO/ISR.
 */

typedef struct {
    bool active;
    uint32_t expected_seq;
    /* heap_caps_malloc'd at BEGIN, freed at the end of every attempt. */
    uint8_t *staging;
    size_t staged_length;
    char manifest_json[MANIFEST_BUFFER_CAPACITY];
    uint32_t manifest_byte_length;
    char manifest_sha256[65];
    char manifest_bundle_id[128];
    uint32_t manifest_generation;
    TickType_t last_activity_tick;
} transport_session_t;

typedef struct {
    runtime_probe_t *probe;
    transport_session_t session;
    char line[LINE_BUFFER_CAPACITY];
    size_t line_length;
} transport_state_t;

static transport_state_t s_state;

static void write_response(const char *line)
{
    /* Leading + trailing newline: its own line even if a partial (unterminated) log write is mid-flight. */
    printf("\n%s\n", line);
    fflush(stdout);
}

static void reset_session(transport_session_t *session)
{
    if (session->staging != NULL) {
        heap_caps_free(session->staging);
    }
    memset(session, 0, sizeof(*session));
}

static bool find_number_field(const char *json, const char *key, uint32_t *out)
{
    char pattern[32];
    snprintf(pattern, sizeof(pattern), "\"%s\":", key);
    const char *at = strstr(json, pattern);
    if (at == NULL) return false;
    at += strlen(pattern);
    return sscanf(at, "%" SCNu32, out) == 1;
}

static bool find_string_field(const char *json, const char *key, char *out, size_t out_capacity)
{
    char pattern[32];
    snprintf(pattern, sizeof(pattern), "\"%s\":\"", key);
    const char *at = strstr(json, pattern);
    if (at == NULL) return false;
    at += strlen(pattern);
    const char *end = strchr(at, '"');
    if (end == NULL) return false;
    const size_t length = (size_t)(end - at);
    if (length >= out_capacity) return false;
    memcpy(out, at, length);
    out[length] = '\0';
    return true;
}

/*
 * Manifests are machine-generated by @tsx-lvgl/bundler (packages/bundler/src/index.ts)
 * with a fixed key order and no nested objects/arrays before these keys, so
 * plain strstr/sscanf extraction is safe. This is not a general JSON parser.
 */
static bool parse_manifest_fields(transport_session_t *session)
{
    if (!find_string_field(session->manifest_json, "bundleId", session->manifest_bundle_id,
                            sizeof(session->manifest_bundle_id))) {
        return false;
    }
    if (!find_number_field(session->manifest_json, "generation", &session->manifest_generation)) return false;
    if (!find_string_field(session->manifest_json, "sha256", session->manifest_sha256,
                            sizeof(session->manifest_sha256))) {
        return false;
    }
    if (strlen(session->manifest_sha256) != 64U) return false;
    if (!find_number_field(session->manifest_json, "byteLength", &session->manifest_byte_length)) return false;
    return true;
}

static void handle_begin(transport_state_t *state, const char *base64_manifest)
{
    if (state->session.active) {
        write_response("TSXB ERR busy");
        return;
    }
    if (base64_manifest[0] == '\0') {
        write_response("TSXB ERR frame");
        return;
    }

    transport_session_t *session = &state->session;
    unsigned char decoded[MANIFEST_BUFFER_CAPACITY];
    size_t decoded_length = 0;
    const int rc = mbedtls_base64_decode(decoded, sizeof(decoded) - 1U, &decoded_length,
                                         (const unsigned char *)base64_manifest, strlen(base64_manifest));
    if (rc == MBEDTLS_ERR_BASE64_INVALID_CHARACTER) {
        write_response("TSXB ERR base64");
        return;
    }
    if (rc != 0) {
        write_response("TSXB ERR frame");
        return;
    }
    decoded[decoded_length] = '\0';

    memset(session, 0, sizeof(*session));
    memcpy(session->manifest_json, decoded, decoded_length + 1U);

    if (!parse_manifest_fields(session)) {
        write_response("TSXB ERR malformed-manifest");
        return;
    }
    if (session->manifest_byte_length > RUNTIME_BUNDLE_MAX_BYTES) {
        write_response("TSXB ERR bundle-too-large");
        return;
    }

    /* +1: room to NUL-terminate the staged bytes as ASCII JS source text at END. */
    session->staging = heap_caps_malloc(RUNTIME_BUNDLE_MAX_BYTES + 1U, MALLOC_CAP_SPIRAM);
    if (session->staging == NULL) {
        write_response("TSXB ERR frame");
        return;
    }

    session->active = true;
    session->last_activity_tick = xTaskGetTickCount();

    char response[160];
    snprintf(response, sizeof(response), "TSXB RDY maxBytes=%u protocol=%d board=%s lastGeneration=%u",
             (unsigned)RUNTIME_BUNDLE_MAX_BYTES, RUNTIME_PROBE_PROTOCOL_VERSION, RUNTIME_PROBE_BOARD_ID,
             (unsigned)runtime_probe_last_generation(state->probe));
    write_response(response);
}

static void handle_data(transport_state_t *state, const char *remainder)
{
    transport_session_t *session = &state->session;
    if (!session->active) return;

    unsigned seq = 0;
    int consumed = 0;
    if (sscanf(remainder, "%u%n", &seq, &consumed) != 1) {
        reset_session(session);
        write_response("TSXB ERR frame");
        return;
    }
    const char *payload = remainder + consumed;
    while (*payload == ' ') payload++;
    if (*payload == '\0') {
        reset_session(session);
        write_response("TSXB ERR frame");
        return;
    }

    if (seq != session->expected_seq + 1U) {
        reset_session(session);
        write_response("TSXB ERR sequence");
        return;
    }

    unsigned char decoded[DATA_CHUNK_MAX_BYTES];
    size_t decoded_length = 0;
    const int rc = mbedtls_base64_decode(decoded, sizeof(decoded), &decoded_length,
                                         (const unsigned char *)payload, strlen(payload));
    if (rc == MBEDTLS_ERR_BASE64_INVALID_CHARACTER) {
        reset_session(session);
        write_response("TSXB ERR base64");
        return;
    }
    if (rc != 0 || session->staged_length + decoded_length > RUNTIME_BUNDLE_MAX_BYTES) {
        reset_session(session);
        write_response("TSXB ERR overflow");
        return;
    }

    memcpy(session->staging + session->staged_length, decoded, decoded_length);
    session->staged_length += decoded_length;
    session->expected_seq = seq;
    session->last_activity_tick = xTaskGetTickCount();

    char response[32];
    snprintf(response, sizeof(response), "TSXB ACK %u", seq);
    write_response(response);
}

static void handle_end(transport_state_t *state, const char *remainder)
{
    transport_session_t *session = &state->session;
    if (!session->active) return;

    unsigned count = 0;
    if (sscanf(remainder, "%u", &count) != 1) {
        reset_session(session);
        write_response("TSXB ERR frame");
        return;
    }
    if (count != session->expected_seq) {
        reset_session(session);
        write_response("TSXB ERR sequence");
        return;
    }
    if (session->staged_length != session->manifest_byte_length) {
        reset_session(session);
        write_response("TSXB ERR byte-length-mismatch");
        return;
    }

    unsigned char digest[32];
    mbedtls_sha256(session->staging, session->staged_length, digest, 0);
    char digest_hex[65];
    for (int index = 0; index < 32; index++) {
        snprintf(digest_hex + index * 2, 3, "%02x", digest[index]);
    }
    if (strcmp(digest_hex, session->manifest_sha256) != 0) {
        reset_session(session);
        write_response("TSXB ERR sha256");
        return;
    }

    /* Safe: staging is RUNTIME_BUNDLE_MAX_BYTES + 1 and staged_length <= manifest_byte_length <= RUNTIME_BUNDLE_MAX_BYTES. */
    session->staging[session->staged_length] = '\0';

    const runtime_probe_reload_result_t result = runtime_probe_stage_reload(
        state->probe, session->manifest_json, (const char *)session->staging, RELOAD_TIMEOUT_MS);

    char response[192];
    switch (result.kind) {
        case RUNTIME_PROBE_RELOAD_COMMITTED:
            snprintf(response, sizeof(response), "TSXB OK bundle=%s generation=%u epoch=%u",
                     session->manifest_bundle_id, (unsigned)session->manifest_generation, (unsigned)result.epoch);
            break;
        case RUNTIME_PROBE_RELOAD_ROLLED_BACK:
            snprintf(response, sizeof(response), "TSXB ERR evaluate-rolled-back");
            break;
        case RUNTIME_PROBE_RELOAD_REJECTED:
            snprintf(response, sizeof(response), "TSXB ERR %s", result.reason);
            break;
        case RUNTIME_PROBE_RELOAD_TIMEOUT:
        default:
            snprintf(response, sizeof(response), "TSXB ERR timeout");
            break;
    }
    write_response(response);
    reset_session(session);
}

static void handle_abort(transport_state_t *state)
{
    if (!state->session.active) return;
    reset_session(&state->session);
    /* No response, per spec. */
}

static void handle_line(transport_state_t *state, const char *line)
{
    if (strncmp(line, "TSXB ", 5) != 0) return; /* noise: not our protocol */

    const char *rest = line + 5;
    const char *space = strchr(rest, ' ');
    const size_t tag_length = space != NULL ? (size_t)(space - rest) : strlen(rest);
    const char *remainder = space != NULL ? space + 1 : "";

    if (tag_length == 5U && strncmp(rest, "BEGIN", 5) == 0) {
        handle_begin(state, remainder);
        return;
    }
    if (tag_length == 4U && strncmp(rest, "DATA", 4) == 0) {
        handle_data(state, remainder);
        return;
    }
    if (tag_length == 3U && strncmp(rest, "END", 3) == 0) {
        handle_end(state, remainder);
        return;
    }
    if (tag_length == 5U && strncmp(rest, "ABORT", 5) == 0) {
        handle_abort(state);
        return;
    }

    /* Malformed TSXB-prefixed line: noise while idle, a protocol error mid-transfer. */
    if (state->session.active) {
        /* The remainder can contain bundle bytes; keep payload out of UART logs. */
        ESP_LOGW(TAG, "PROBE transport frame_error tag_length=%u", (unsigned)tag_length);
        reset_session(&state->session);
        write_response("TSXB ERR frame");
    }
}

static void bundle_transport_task(void *arg)
{
    transport_state_t *state = arg;
    uint8_t chunk[READ_CHUNK_BYTES];

    while (true) {
        const int read = usb_serial_jtag_read_bytes(chunk, sizeof(chunk), pdMS_TO_TICKS(READ_POLL_MS));
        for (int index = 0; index < read; index++) {
            const char character = (char)chunk[index];
            if (character == '\n') {
                state->line[state->line_length] = '\0';
                handle_line(state, state->line);
                state->line_length = 0;
                continue;
            }
            if (character == '\r') continue;
            if (state->line_length + 1U < sizeof(state->line)) {
                state->line[state->line_length++] = character;
            } else {
                /* Line too long to be any valid frame; drop it and resync on the next '\n'. */
                state->line_length = 0;
            }
        }

        if (state->session.active) {
            const TickType_t elapsed = xTaskGetTickCount() - state->session.last_activity_tick;
            if (elapsed > pdMS_TO_TICKS(INACTIVITY_TIMEOUT_MS)) {
                ESP_LOGW(TAG, "PROBE transport inactivity_timeout");
                reset_session(&state->session);
                /* No response, per spec. */
            }
        }
    }
}

esp_err_t bundle_transport_start(runtime_probe_t *probe)
{
    memset(&s_state, 0, sizeof(s_state));
    s_state.probe = probe;

    usb_serial_jtag_driver_config_t usj_config = USB_SERIAL_JTAG_DRIVER_CONFIG_DEFAULT();
    usj_config.rx_buffer_size = 1024;
    const esp_err_t install_result = usb_serial_jtag_driver_install(&usj_config);
    if (install_result != ESP_OK) return install_result;

    if (xTaskCreate(bundle_transport_task, "bundle_transport", 8192, &s_state, 3, NULL) != pdPASS) {
        (void)usb_serial_jtag_driver_uninstall();
        return ESP_FAIL;
    }
    return ESP_OK;
}
