// GENERATED by scripts/build-kernel.mjs \u2014 do not edit.
// Source packages: core, sensors, runtime, device (packages/*/src).
//
// Define order below is irrelevant: __tsxRequire resolves modules lazily
// at call time, not at define time. Packages are emitted in a fixed order
// (core, sensors, runtime, device, then aliases) purely for byte determinism.
"use strict";
var __tsxModules = {};
var __tsxCache = {};
function __tsxDefine(name, factory) {
  __tsxModules[name] = factory;
}
function __tsxRequire(name) {
  if (Object.prototype.hasOwnProperty.call(__tsxCache, name)) {
    return __tsxCache[name].exports;
  }
  if (!Object.prototype.hasOwnProperty.call(__tsxModules, name)) {
    throw new Error("unknown module: " + name);
  }
  var module = { exports: {} };
  __tsxCache[name] = module;
  __tsxModules[name](__tsxRequire, module, module.exports);
  return module.exports;
}

__tsxDefine("@tsx-lvgl/core/index.js", function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Button = exports.Text = exports.View = exports.Screen = exports.elementTypes = exports.Fragment = void 0;
exports.createVNode = createVNode;
exports.normalizeChildren = normalizeChildren;
exports.isVNode = isVNode;
exports.Fragment = Symbol.for("@tsx-lvgl/core/Fragment");
exports.elementTypes = ["Screen", "View", "Text", "Button"];
exports.Screen = "Screen";
exports.View = "View";
exports.Text = "Text";
exports.Button = "Button";
const elementTypeNames = new Set(exports.elementTypes);
const emptyChildren = Object.freeze([]);
const emptyProps = Object.freeze({});
function createVNode(type, props = emptyProps, children = emptyChildren, key = null) {
    const kind = type === exports.Fragment
        ? "fragment"
        : typeof type === "function"
            ? "component"
            : "element";
    return Object.freeze({
        kind,
        type,
        key,
        props: Object.freeze(props ?? emptyProps),
        children: normalizeChildren(children),
    });
}
function normalizeChildren(children) {
    const normalized = [];
    for (const child of children)
        visitChild(child, normalized);
    return normalized.length === 0 ? emptyChildren : Object.freeze(normalized);
}
function visitChild(value, out) {
    if (Array.isArray(value)) {
        for (const child of value)
            visitChild(child, out);
        return;
    }
    if (value === null || value === undefined || typeof value === "boolean")
        return;
    if (typeof value === "string" || typeof value === "number") {
        out.push(createVNode(exports.Text, { text: value }));
        return;
    }
    if (!isVNode(value)) {
        throw new Error("Invalid child: expected a VNode, string, number, or empty value");
    }
    out.push(value);
}
function isVNode(value) {
    if (value === null || typeof value !== "object")
        return false;
    const candidate = value;
    const type = candidate.type;
    const validKind = ((candidate.kind === "element" && elementTypeNames.has(type)) ||
        (candidate.kind === "component" && typeof type === "function") ||
        (candidate.kind === "fragment" && type === exports.Fragment));
    const validKey = candidate.key === null || typeof candidate.key === "string" || typeof candidate.key === "number";
    return (validKind &&
        validKey &&
        typeof candidate.props === "object" &&
        candidate.props !== null &&
        Array.isArray(candidate.children));
}

});
__tsxDefine("@tsx-lvgl/core/jsx-runtime.js", function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.jsxs = exports.Fragment = void 0;
exports.jsx = jsx;
const index_js_1 = require("@tsx-lvgl/core/index.js");
exports.Fragment = index_js_1.Fragment;
function jsx(type, props, key = null) {
    if (props === null)
        return (0, index_js_1.createVNode)(type, null, undefined, key);
    const { children, ...elementProps } = props;
    return (0, index_js_1.createVNode)(type, elementProps, [children], key);
}
exports.jsxs = jsx;

});
__tsxDefine("@tsx-lvgl/sensors/index.js", function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.motionSchema = exports.isShake = exports.isMotionSample = void 0;
exports.createSensorRegistry = createSensorRegistry;
exports.schemaKey = schemaKey;
exports.subscribeSensor = subscribeSensor;
exports.acceptsSensorSample = acceptsSensorSample;
var motion_js_1 = require("@tsx-lvgl/sensors/motion.js");
Object.defineProperty(exports, "isMotionSample", { enumerable: true, get: function () { return motion_js_1.isMotionSample; } });
Object.defineProperty(exports, "isShake", { enumerable: true, get: function () { return motion_js_1.isShake; } });
Object.defineProperty(exports, "motionSchema", { enumerable: true, get: function () { return motion_js_1.motionSchema; } });
function createSensorRegistry(sensors) {
    const byKey = new Map(sensors.map((sensor) => [schemaKey(sensor.schema), sensor]));
    return {
        get(schema) {
            return byKey.get(schemaKey(schema));
        },
    };
}
function schemaKey(schema) {
    return `${schema.id}@${schema.version}`;
}
function subscribeSensor(sensor, reloadEpoch, onSample, onError) {
    let cancelled = false;
    let lastSequence = 0;
    const context = {
        reloadEpoch,
        isCancelled: () => cancelled,
    };
    const accept = (next) => {
        if (!cancelled) {
            if (!acceptsSensorSample(next, sensor.schema, reloadEpoch, lastSequence))
                return;
            lastSequence = next.sequence;
            onSample(next);
        }
    };
    const unsubscribe = sensor.subscribe(accept, context);
    void sensor.read(context).then(accept, (error) => {
        if (!cancelled)
            onError(error);
    });
    return {
        cancel() {
            if (cancelled)
                return;
            cancelled = true;
            unsubscribe();
        },
    };
}
function acceptsSensorSample(sample, schema, reloadEpoch, lastSequence) {
    if (sample.sensorId !== schema.id)
        return false;
    if (sample.schemaVersion !== schema.version)
        return false;
    if (sample.reloadEpoch !== reloadEpoch)
        return false;
    if (!Number.isSafeInteger(sample.sequence) || sample.sequence <= lastSequence)
        return false;
    if (sample.value === undefined)
        return sample.status !== "ok";
    return schema.validate(sample.value);
}

});
__tsxDefine("@tsx-lvgl/sensors/motion.js", function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.motionSchema = void 0;
exports.isMotionSample = isMotionSample;
exports.isShake = isShake;
exports.motionSchema = {
    id: "board.qmi8658.motion",
    version: 1,
    unit: "m/s2+dps",
    validate: isMotionSample,
};
const EARTH_GRAVITY_MPS2 = 9.80665;
const SHAKE_ACCELERATION_DELTA_MPS2 = 6;
const SHAKE_ANGULAR_VELOCITY_DPS = 180;
function isMotionSample(value) {
    if (typeof value !== "object" || value === null)
        return false;
    const candidate = value;
    return isVector(candidate.accelerationMps2) && isVector(candidate.angularVelocityDps);
}
function isShake(sample) {
    const accelerationMagnitude = magnitude(sample.accelerationMps2);
    const rotationMagnitude = magnitude(sample.angularVelocityDps);
    return Math.abs(accelerationMagnitude - EARTH_GRAVITY_MPS2) >= SHAKE_ACCELERATION_DELTA_MPS2
        || rotationMagnitude >= SHAKE_ANGULAR_VELOCITY_DPS;
}
function isVector(value) {
    return Array.isArray(value)
        && value.length === 3
        && value.every((axis) => Number.isFinite(axis));
}
function magnitude(vector) {
    return Math.hypot(vector[0], vector[1], vector[2]);
}

});
__tsxDefine("@tsx-lvgl/runtime/bundle.js", function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RUNTIME_BUNDLE_MAX_BYTES = exports.PROTOCOL_VERSION = void 0;
exports.validateRuntimeBundle = validateRuntimeBundle;
exports.PROTOCOL_VERSION = 1;
exports.RUNTIME_BUNDLE_MAX_BYTES = 262144;
function validateRuntimeBundle(bundle, policy) {
    const { manifest, source } = bundle;
    if (manifest.bundleId.length === 0)
        return { ok: false, reason: "empty-bundle-id" };
    if (manifest.format !== "js" && manifest.format !== "bytecode")
        return { ok: false, reason: "unsupported-format" };
    if (manifest.engine !== policy.engine)
        return { ok: false, reason: "engine-mismatch" };
    if (manifest.protocolVersion !== policy.protocolVersion)
        return { ok: false, reason: "protocol-mismatch" };
    if (manifest.boardId !== policy.boardId)
        return { ok: false, reason: "board-mismatch" };
    if (!Number.isSafeInteger(manifest.generation) || manifest.generation <= policy.lastGeneration) {
        return { ok: false, reason: "generation-not-monotonic" };
    }
    if (!/^[a-f0-9]{64}$/.test(manifest.sha256))
        return { ok: false, reason: "invalid-hash" };
    if (manifest.byteLength !== source.byteLength)
        return { ok: false, reason: "byte-length-mismatch" };
    if (source.byteLength > policy.maxBytes)
        return { ok: false, reason: "bundle-too-large" };
    return { ok: true, bundle: { manifest, source: source.slice() } };
}

});
__tsxDefine("@tsx-lvgl/runtime/engine.js", function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.decodeAsciiSource = decodeAsciiSource;
exports.createProgramEngine = createProgramEngine;
const core_1 = require("@tsx-lvgl/core");
function decodeAsciiSource(source) {
    const chars = new Array(source.length);
    for (let index = 0; index < source.length; index++) {
        const byte = source[index];
        if (byte >= 0x80)
            throw new Error(`non-ascii byte at ${index}`);
        chars[index] = String.fromCharCode(byte);
    }
    return chars.join("");
}
function createProgramEngine(name, resolve) {
    return {
        name,
        evaluate(source, _manifest) {
            const code = decodeAsciiSource(source);
            const run = new Function("require", "module", "exports", code);
            const module = { exports: {} };
            run(resolve, module, module.exports);
            const value = module.exports.default;
            if (typeof value === "function")
                return (0, core_1.createVNode)(value);
            if ((0, core_1.isVNode)(value))
                return value;
            throw new Error("bundle default export must be a component or VNode");
        },
    };
}

});
__tsxDefine("@tsx-lvgl/runtime/fiber.js", function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.mountFiber = mountFiber;
exports.reconcileFiber = reconcileFiber;
exports.unmountFiber = unmountFiber;
exports.syncHostAncestor = syncHostAncestor;
exports.collectHostRoots = collectHostRoots;
exports.singleHostRoot = singleHostRoot;
const core_1 = require("@tsx-lvgl/core");
const hooks_js_1 = require("@tsx-lvgl/runtime/hooks.js");
function mountFiber(session, vnode, parent) {
    const fiber = {
        vnode,
        parent,
        depth: parent === null ? 0 : parent.depth + 1,
        children: [],
        hooks: undefined,
        hookIndex: 0,
        active: true,
        instance: undefined,
        hostOrder: undefined,
        mark: undefined,
    };
    try {
        if (vnode.kind === "element") {
            fiber.instance = session.host.createInstance(vnode.type, vnode.props);
        }
        renderFiber(session, fiber);
        return fiber;
    }
    catch (error) {
        unmountFiber(session, fiber);
        throw error;
    }
}
function reconcileFiber(session, fiber, vnode) {
    const previous = fiber.vnode;
    fiber.vnode = vnode;
    if (vnode.kind === "element" && !sameProps(previous.props, vnode.props)) {
        session.host.updateInstance(fiber.instance, vnode.type, previous.props, vnode.props);
    }
    renderFiber(session, fiber);
}
function unmountFiber(session, fiber) {
    fiber.active = false;
    for (const child of fiber.children)
        unmountFiber(session, child);
    fiber.children.length = 0;
    const hooks = fiber.hooks;
    if (hooks !== undefined) {
        fiber.hooks = undefined;
        try {
            (0, hooks_js_1.releaseHooks)(hooks);
        }
        catch (error) {
            session.reportError(error);
        }
    }
    const instance = fiber.instance;
    if (instance !== undefined) {
        const hostParent = findHostParent(fiber);
        const attached = hostParent === undefined
            ? session.isAttached()
            : hostParent.hostOrder?.includes(instance) === true;
        if (attached) {
            session.host.removeChild(hostParent?.instance ?? null, instance);
        }
        session.host.dispose(instance);
        fiber.instance = undefined;
    }
    fiber.hostOrder = undefined;
}
function syncHostAncestor(session, fiber) {
    for (let ancestor = fiber.parent; ancestor !== null; ancestor = ancestor.parent) {
        if (ancestor.vnode.kind !== "element")
            continue;
        syncHostOrder(session, ancestor);
        return;
    }
}
function collectHostRoots(fiber, out) {
    if (fiber.vnode.kind === "element") {
        out.push(fiber.instance);
        return;
    }
    for (const child of fiber.children)
        collectHostRoots(child, out);
}
function singleHostRoot(fiber) {
    const roots = [];
    collectHostRoots(fiber, roots);
    if (roots.length !== 1)
        throw new Error("Runtime roots must resolve to exactly one host instance");
    return roots[0];
}
function renderFiber(session, fiber) {
    const vnode = fiber.vnode;
    if (vnode.kind !== "component") {
        reconcileChildren(session, fiber, vnode.children);
        return;
    }
    const component = vnode.type;
    const output = (0, hooks_js_1.renderWithHooks)(session, fiber, () => component({ ...vnode.props, children: vnode.children }));
    reconcileChildren(session, fiber, (0, core_1.normalizeChildren)([output]));
}
function reconcileChildren(session, parent, next) {
    const previousChildren = parent.children;
    assertUniqueKeys(next);
    const keyed = indexByKey(previousChildren);
    const stamp = Symbol("reconcile-pass");
    const reconciled = [];
    const mounted = [];
    try {
        for (let index = 0; index < next.length; index++) {
            const vnode = next[index];
            const match = findMatch(vnode, index, previousChildren, keyed);
            if (match === undefined) {
                const child = mountFiber(session, vnode, parent);
                mounted.push(child);
                reconciled.push(child);
                continue;
            }
            match.mark = stamp;
            reconcileFiber(session, match, vnode);
            reconciled.push(match);
        }
        for (const child of previousChildren) {
            if (child.mark !== stamp)
                unmountFiber(session, child);
        }
    }
    catch (error) {
        for (let index = mounted.length - 1; index >= 0; index--) {
            unmountFiber(session, mounted[index]);
        }
        throw error;
    }
    previousChildren.length = 0;
    for (const fiber of reconciled)
        previousChildren.push(fiber);
    syncHostOrder(session, parent);
}
function findMatch(vnode, index, previousChildren, keyed) {
    if (vnode.key !== null) {
        const candidate = keyed.get(vnode.key);
        return candidate !== undefined && candidate.vnode.type === vnode.type ? candidate : undefined;
    }
    const slot = previousChildren[index];
    return slot !== undefined && slot.vnode.key === null && slot.vnode.type === vnode.type
        ? slot
        : undefined;
}
function syncHostOrder(session, parent) {
    if (parent.vnode.kind !== "element")
        return;
    const roots = [];
    for (const child of parent.children)
        collectHostRoots(child, roots);
    if (sameInstances(parent.hostOrder, roots))
        return;
    parent.hostOrder = roots;
    const parentInstance = parent.instance;
    for (let index = 0; index < roots.length; index++) {
        session.host.insertChild(parentInstance, roots[index], index);
    }
}
function assertUniqueKeys(children) {
    let keys;
    for (const child of children) {
        if (child.key === null)
            continue;
        keys ?? (keys = new Set());
        if (keys.has(child.key))
            throw new Error(`Duplicate child key: ${String(child.key)}`);
        keys.add(child.key);
    }
}
function indexByKey(children) {
    const keyed = new Map();
    for (const child of children) {
        keyed.set(child.vnode.key, child);
    }
    return keyed;
}
function findHostParent(fiber) {
    for (let ancestor = fiber.parent; ancestor !== null; ancestor = ancestor.parent) {
        if (ancestor.vnode.kind === "element")
            return ancestor;
    }
    return undefined;
}
function sameInstances(previous, next) {
    if (previous === undefined)
        return false;
    if (previous.length !== next.length)
        return false;
    return next.every((instance, index) => previous[index] === instance);
}
function sameProps(previous, next) {
    let count = 0;
    for (const key in next) {
        if (!Object.is(previous[key], next[key]))
            return false;
        count++;
    }
    return Object.keys(previous).length === count;
}

});
__tsxDefine("@tsx-lvgl/runtime/hooks.js", function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.renderWithHooks = renderWithHooks;
exports.useState = useState;
exports.useEffect = useEffect;
exports.useInterval = useInterval;
exports.useSensor = useSensor;
exports.releaseHooks = releaseHooks;
const sensors_1 = require("@tsx-lvgl/sensors");
let currentSession = null;
let currentFiber = null;
function renderWithHooks(session, fiber, render) {
    const previousSession = currentSession;
    const previousFiber = currentFiber;
    currentSession = session;
    currentFiber = fiber;
    fiber.hookIndex = 0;
    try {
        return render();
    }
    finally {
        currentSession = previousSession;
        currentFiber = previousFiber;
    }
}
function useState(initial) {
    const fiber = requireFiber("useState");
    const session = currentSession;
    const hooks = fiber.hooks ?? (fiber.hooks = []);
    const index = fiber.hookIndex++;
    const existing = hooks[index];
    if (existing === undefined) {
        const hook = {
            kind: "state",
            value: typeof initial === "function" ? initial() : initial,
            setter: (update) => {
                if (!session.isActive() || !fiber.active)
                    return;
                const next = typeof update === "function"
                    ? update(hook.value)
                    : update;
                if (Object.is(next, hook.value))
                    return;
                hook.value = next;
                session.requestUpdate(fiber);
            },
        };
        hooks[index] = hook;
        return [hook.value, hook.setter];
    }
    if (existing.kind !== "state")
        throw new Error("Hook order changed: expected state hook");
    const hook = existing;
    return [hook.value, hook.setter];
}
function useEffect(effect, dependencies) {
    const fiber = requireFiber("useEffect");
    const session = currentSession;
    const hooks = fiber.hooks ?? (fiber.hooks = []);
    const index = fiber.hookIndex++;
    const existing = hooks[index];
    if (existing === undefined) {
        const hook = { kind: "effect", dependencies, effect, cleanup: undefined };
        hooks[index] = hook;
        session.enqueueEffect(hook);
        return;
    }
    if (existing.kind !== "effect")
        throw new Error("Hook order changed: expected effect hook");
    const changed = dependencies === undefined || existing.dependencies === undefined
        ? true
        : !sameDependencies(existing.dependencies, dependencies);
    if (!changed)
        return;
    existing.dependencies = dependencies;
    existing.effect = effect;
    session.enqueueEffect(existing);
}
function useInterval(callback, periodMs) {
    if (!Number.isInteger(periodMs) || periodMs <= 0) {
        throw new Error("useInterval period must be a positive integer");
    }
    const fiber = requireFiber("useInterval");
    const session = currentSession;
    const [slot] = useState(() => createCallbackSlot(callback));
    slot.callback = callback;
    useEffect(() => {
        const handle = session.scheduler.setInterval(() => {
            if (session.isActive() && fiber.active)
                slot.callback();
        }, periodMs);
        return () => session.scheduler.clearInterval(handle);
    }, [periodMs]);
}
function useSensor(schema) {
    requireFiber("useSensor");
    const session = currentSession;
    const sensor = session.capabilities.sensors.get(schema);
    const [sample, setSample] = useState(undefined);
    useEffect(() => {
        if (sensor === undefined)
            return;
        const subscription = (0, sensors_1.subscribeSensor)(sensor, session.epoch, setSample, (error) => session.reportError(error));
        return () => subscription.cancel();
    }, [sensor]);
    return sample;
}
function releaseHooks(hooks) {
    let firstError;
    let hasError = false;
    for (const hook of hooks) {
        switch (hook.kind) {
            case "effect": {
                const cleanup = hook.cleanup;
                hook.cleanup = undefined;
                try {
                    cleanup?.();
                }
                catch (error) {
                    if (!hasError) {
                        firstError = error;
                        hasError = true;
                    }
                }
                break;
            }
        }
    }
    if (hasError)
        throw firstError;
}
function createCallbackSlot(callback) {
    const slot = Object.create(null);
    slot.callback = callback;
    return slot;
}
function requireFiber(name) {
    if (currentFiber === null)
        throw new Error(`${name} must be called while rendering a component`);
    return currentFiber;
}
function sameDependencies(previous, next) {
    if (previous.length !== next.length)
        return false;
    for (const [index, dependency] of next.entries()) {
        if (!Object.is(previous[index], dependency))
            return false;
    }
    return true;
}

});
__tsxDefine("@tsx-lvgl/runtime/host.js", function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });

});
__tsxDefine("@tsx-lvgl/runtime/index.js", function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.decodeAsciiSource = exports.createProgramEngine = exports.validateRuntimeBundle = exports.RUNTIME_BUNDLE_MAX_BYTES = exports.PROTOCOL_VERSION = exports.useState = exports.useSensor = exports.useInterval = exports.useEffect = exports.Runtime = void 0;
var runtime_js_1 = require("@tsx-lvgl/runtime/runtime.js");
Object.defineProperty(exports, "Runtime", { enumerable: true, get: function () { return runtime_js_1.Runtime; } });
var hooks_js_1 = require("@tsx-lvgl/runtime/hooks.js");
Object.defineProperty(exports, "useEffect", { enumerable: true, get: function () { return hooks_js_1.useEffect; } });
Object.defineProperty(exports, "useInterval", { enumerable: true, get: function () { return hooks_js_1.useInterval; } });
Object.defineProperty(exports, "useSensor", { enumerable: true, get: function () { return hooks_js_1.useSensor; } });
Object.defineProperty(exports, "useState", { enumerable: true, get: function () { return hooks_js_1.useState; } });
var bundle_js_1 = require("@tsx-lvgl/runtime/bundle.js");
Object.defineProperty(exports, "PROTOCOL_VERSION", { enumerable: true, get: function () { return bundle_js_1.PROTOCOL_VERSION; } });
Object.defineProperty(exports, "RUNTIME_BUNDLE_MAX_BYTES", { enumerable: true, get: function () { return bundle_js_1.RUNTIME_BUNDLE_MAX_BYTES; } });
Object.defineProperty(exports, "validateRuntimeBundle", { enumerable: true, get: function () { return bundle_js_1.validateRuntimeBundle; } });
var engine_js_1 = require("@tsx-lvgl/runtime/engine.js");
Object.defineProperty(exports, "createProgramEngine", { enumerable: true, get: function () { return engine_js_1.createProgramEngine; } });
Object.defineProperty(exports, "decodeAsciiSource", { enumerable: true, get: function () { return engine_js_1.decodeAsciiSource; } });

});
__tsxDefine("@tsx-lvgl/runtime/runtime.js", function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Runtime = void 0;
const sensors_1 = require("@tsx-lvgl/sensors");
const bundle_js_1 = require("@tsx-lvgl/runtime/bundle.js");
const session_js_1 = require("@tsx-lvgl/runtime/session.js");
const noCapabilities = { sensors: (0, sensors_1.createSensorRegistry)([]) };
class Runtime {
    constructor(options) {
        this.options = options;
        this.activeSession = null;
        this.currentEpoch = 0;
    }
    get epoch() {
        return this.currentEpoch;
    }
    get host() {
        return this.options.host;
    }
    get scheduler() {
        return this.options.scheduler;
    }
    get capabilities() {
        return this.options.capabilities ?? noCapabilities;
    }
    mount(root) {
        if (this.activeSession !== null)
            throw new Error("Runtime already has a mounted root");
        const result = this.commit(root);
        if (result.status === "rolled_back")
            throw result.error;
        return this.activeSession;
    }
    reload(root) {
        return this.commit(root);
    }
    reloadBundle(bundle, policy, engine) {
        const validation = (0, bundle_js_1.validateRuntimeBundle)(bundle, policy);
        if (!validation.ok)
            return { status: "rejected", reason: validation.reason };
        if (engine.name !== validation.bundle.manifest.engine) {
            return { status: "rejected", reason: "engine-mismatch" };
        }
        try {
            const root = engine.evaluate(validation.bundle.source, validation.bundle.manifest);
            return this.reload(root);
        }
        catch (error) {
            return { status: "rolled_back", epoch: this.currentEpoch, error };
        }
    }
    unmount() {
        const session = this.activeSession;
        if (session === null)
            return;
        this.options.host.replaceRoot(null, session.rootHost);
        session.detach();
        session.dispose();
        this.activeSession = null;
    }
    reportError(error) {
        this.options.onError?.(error);
    }
    sessionDisposed(session) {
        if (this.activeSession === session)
            this.activeSession = null;
    }
    commit(root) {
        const previous = this.activeSession;
        const candidate = new session_js_1.Session(this, root, this.currentEpoch + 1);
        let rootSwapStarted = false;
        const restorePreviousRoot = () => {
            if (!rootSwapStarted)
                return;
            try {
                this.options.host.replaceRoot(previous?.rootHost ?? null, candidate.rootHost);
            }
            catch (restoreError) {
                this.reportError(restoreError);
            }
        };
        try {
            candidate.build();
            rootSwapStarted = true;
            this.options.host.replaceRoot(candidate.rootHost, previous?.rootHost ?? null);
            candidate.attach();
            try {
                candidate.flushEffects();
            }
            catch (error) {
                restorePreviousRoot();
                candidate.detach();
                candidate.dispose();
                return { status: "rolled_back", epoch: this.currentEpoch, error };
            }
            this.activeSession = candidate;
            this.currentEpoch = candidate.epoch;
            try {
                previous?.dispose();
            }
            catch (error) {
                this.reportError(error);
            }
            return { status: "committed", epoch: candidate.epoch };
        }
        catch (error) {
            restorePreviousRoot();
            candidate.dispose();
            return { status: "rolled_back", epoch: this.currentEpoch, error };
        }
    }
}
exports.Runtime = Runtime;

});
__tsxDefine("@tsx-lvgl/runtime/session.js", function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Session = void 0;
const fiber_js_1 = require("@tsx-lvgl/runtime/fiber.js");
class Session {
    constructor(context, root, epoch) {
        this.context = context;
        this.root = root;
        this.epoch = epoch;
        this.rootFiber = null;
        this.attached = false;
        this.disposed = false;
        this.flushQueued = false;
        this.pendingEffects = [];
        this.dirty = new Set();
    }
    get host() {
        return this.context.host;
    }
    get scheduler() {
        return this.context.scheduler;
    }
    get capabilities() {
        return this.context.capabilities;
    }
    get rootHost() {
        return this.hostRoot;
    }
    build() {
        this.rootFiber = (0, fiber_js_1.mountFiber)(this, this.root, null);
        this.hostRoot = (0, fiber_js_1.singleHostRoot)(this.rootFiber);
    }
    attach() {
        this.attached = true;
    }
    detach() {
        this.attached = false;
    }
    isAttached() {
        return this.attached;
    }
    isActive() {
        return !this.disposed;
    }
    reportError(error) {
        this.context.reportError(error);
    }
    requestUpdate(fiber) {
        if (this.disposed || !fiber.active)
            return;
        this.dirty.add(fiber);
        if (this.flushQueued)
            return;
        this.flushQueued = true;
        this.context.scheduler.enqueue(() => this.flush());
    }
    enqueueEffect(hook) {
        this.pendingEffects.push(hook);
    }
    flushEffects() {
        const pending = this.pendingEffects;
        let cursor = 0;
        try {
            for (const [index, hook] of pending.entries()) {
                cursor = index + 1;
                const cleanup = hook.cleanup;
                hook.cleanup = undefined;
                cleanup?.();
                hook.cleanup = hook.effect();
            }
        }
        finally {
            pending.splice(0, cursor);
        }
    }
    dispose() {
        this.disposed = true;
        if (this.rootFiber !== null) {
            (0, fiber_js_1.unmountFiber)(this, this.rootFiber);
            this.rootFiber = null;
        }
        this.pendingEffects.length = 0;
        this.dirty.clear();
        this.attached = false;
        this.context.sessionDisposed(this);
    }
    flush() {
        this.flushQueued = false;
        const targets = [...this.dirty].sort((left, right) => left.depth - right.depth);
        this.dirty.clear();
        const rendered = new Set();
        try {
            for (const fiber of targets) {
                if (!fiber.active || hasRenderedAncestor(fiber, rendered))
                    continue;
                (0, fiber_js_1.reconcileFiber)(this, fiber, fiber.vnode);
                (0, fiber_js_1.syncHostAncestor)(this, fiber);
                rendered.add(fiber);
            }
            this.flushEffects();
        }
        catch (error) {
            this.context.reportError(error);
        }
    }
}
exports.Session = Session;
function hasRenderedAncestor(fiber, rendered) {
    for (let ancestor = fiber.parent; ancestor !== null; ancestor = ancestor.parent) {
        if (rendered.has(ancestor))
            return true;
    }
    return false;
}

});
__tsxDefine("@tsx-lvgl/device/index.js", function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.encodeAsciiSource = exports.createKernel = exports.createNativeMotionSensor = exports.createDeviceScheduler = exports.createClickRegistry = exports.createLvglHost = void 0;
var lvgl_host_js_1 = require("@tsx-lvgl/device/lvgl-host.js");
Object.defineProperty(exports, "createLvglHost", { enumerable: true, get: function () { return lvgl_host_js_1.createLvglHost; } });
Object.defineProperty(exports, "createClickRegistry", { enumerable: true, get: function () { return lvgl_host_js_1.createClickRegistry; } });
var scheduler_js_1 = require("@tsx-lvgl/device/scheduler.js");
Object.defineProperty(exports, "createDeviceScheduler", { enumerable: true, get: function () { return scheduler_js_1.createDeviceScheduler; } });
var sensors_js_1 = require("@tsx-lvgl/device/sensors.js");
Object.defineProperty(exports, "createNativeMotionSensor", { enumerable: true, get: function () { return sensors_js_1.createNativeMotionSensor; } });
var kernel_js_1 = require("@tsx-lvgl/device/kernel.js");
Object.defineProperty(exports, "createKernel", { enumerable: true, get: function () { return kernel_js_1.createKernel; } });
var kernel_js_2 = require("@tsx-lvgl/device/kernel.js");
Object.defineProperty(exports, "encodeAsciiSource", { enumerable: true, get: function () { return kernel_js_2.encodeAsciiSource; } });

});
__tsxDefine("@tsx-lvgl/device/kernel.js", function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.encodeAsciiSource = encodeAsciiSource;
exports.createKernel = createKernel;
const coreModule = require("@tsx-lvgl/core");
const jsxRuntimeModule = require("@tsx-lvgl/core/jsx-runtime");
const runtime_1 = require("@tsx-lvgl/runtime");
const runtimeModule = require("@tsx-lvgl/runtime");
const sensors_1 = require("@tsx-lvgl/sensors");
const sensorsModule = require("@tsx-lvgl/sensors");
const lvgl_host_js_1 = require("@tsx-lvgl/device/lvgl-host.js");
const scheduler_js_1 = require("@tsx-lvgl/device/scheduler.js");
const sensors_js_1 = require("@tsx-lvgl/device/sensors.js");
const MALFORMED_MANIFEST = Symbol("malformed-manifest");
function parseManifestJson(manifestJson) {
    try {
        return JSON.parse(manifestJson);
    }
    catch {
        return MALFORMED_MANIFEST;
    }
}
function resolveModule(specifier) {
    switch (specifier) {
        case "@tsx-lvgl/core":
            return coreModule;
        case "@tsx-lvgl/core/jsx-runtime":
            return jsxRuntimeModule;
        case "@tsx-lvgl/runtime":
            return runtimeModule;
        case "@tsx-lvgl/sensors":
            return sensorsModule;
        default:
            throw new Error(`unknown module: ${specifier}`);
    }
}
function encodeAsciiSource(text) {
    const codes = new Array(text.length);
    for (let index = 0; index < text.length; index++) {
        const code = text.charCodeAt(index);
        if (code >= 0x80)
            return null;
        codes[index] = code;
    }
    return Uint8Array.from(codes);
}
function createKernel(native) {
    const clicks = (0, lvgl_host_js_1.createClickRegistry)();
    const host = (0, lvgl_host_js_1.createLvglHost)(native.lvgl, clicks);
    const scheduler = (0, scheduler_js_1.createDeviceScheduler)(native.timers);
    const capabilities = {
        sensors: (0, sensors_1.createSensorRegistry)([(0, sensors_js_1.createNativeMotionSensor)(native.sensors, native.timers)]),
    };
    const runtime = new runtime_1.Runtime({
        host,
        scheduler,
        capabilities,
        onError: (error) => native.log(`kernel: error ${String(error)}`),
    });
    native.onClick(clicks.dispatch);
    const resolve = resolveModule;
    const engine = (0, runtime_1.createProgramEngine)("quickjs-ng", resolve);
    let lastGeneration = 0;
    function policy() {
        return {
            protocolVersion: runtime_1.PROTOCOL_VERSION,
            engine: "quickjs-ng",
            boardId: native.boardId,
            maxBytes: runtime_1.RUNTIME_BUNDLE_MAX_BYTES,
            lastGeneration,
        };
    }
    function log(returnValue, logMessage = returnValue) {
        native.log(`kernel: reload ${logMessage}`);
        return returnValue;
    }
    return {
        start(bundle) {
            const validation = (0, runtime_1.validateRuntimeBundle)(bundle, policy());
            if (!validation.ok)
                throw new Error(`bundle rejected: ${validation.reason}`);
            const root = engine.evaluate(validation.bundle.source, validation.bundle.manifest);
            runtime.mount(root);
            lastGeneration = validation.bundle.manifest.generation;
        },
        stageReload(manifestJson, source) {
            const parsedManifest = parseManifestJson(manifestJson);
            if (parsedManifest === MALFORMED_MANIFEST) {
                return log("rejected malformed-manifest", "rejected malformed-manifest (JSON parse error)");
            }
            const manifest = parsedManifest;
            const sourceBytes = encodeAsciiSource(source);
            if (sourceBytes === null)
                return log("rejected non-ascii");
            const bundle = { manifest, source: sourceBytes };
            let result;
            try {
                result = runtime.reloadBundle(bundle, policy(), engine);
            }
            catch {
                return log("rejected malformed-manifest");
            }
            if (result.status === "committed") {
                lastGeneration = manifest.generation;
                return log(`committed ${result.epoch}`, `committed epoch=${result.epoch}`);
            }
            if (result.status === "rolled_back")
                return log("rolled_back");
            return log(`rejected ${result.reason}`);
        },
        pump() {
            scheduler.drain();
        },
        lastGeneration() {
            return lastGeneration;
        },
    };
}

});
__tsxDefine("@tsx-lvgl/device/lvgl-host.js", function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createClickRegistry = createClickRegistry;
exports.createLvglHost = createLvglHost;
function createClickRegistry() {
    const handlers = new Map();
    return {
        set(id, handler) {
            handlers.set(id, handler);
        },
        delete(id) {
            handlers.delete(id);
        },
        dispatch(id) {
            handlers.get(id)?.();
        },
    };
}
const widgetKindByType = {
    Screen: "screen",
    View: "view",
    Text: "text",
    Button: "button",
};
function textOf(props) {
    return String(props.text);
}
function labelOf(props) {
    return String(props.label);
}
function asDevice(instance) {
    return instance;
}
function createLvglHost(native, clicks) {
    return {
        createInstance(type, props) {
            const id = native.create(widgetKindByType[type]);
            if (type === "Text") {
                native.setText(id, textOf(props));
            }
            else if (type === "Button") {
                native.setText(id, labelOf(props));
                const onClick = props.onClick;
                if (typeof onClick === "function") {
                    clicks.set(id, onClick);
                    native.setClickable(id, true);
                }
            }
            const instance = { type, id };
            return instance;
        },
        insertChild(parent, child, index) {
            if (parent === null)
                return;
            native.insert(asDevice(parent).id, asDevice(child).id, index);
        },
        updateInstance(instance, type, previousProps, nextProps) {
            const id = asDevice(instance).id;
            if (type === "Text") {
                const next = textOf(nextProps);
                if (next !== textOf(previousProps))
                    native.setText(id, next);
                return;
            }
            if (type !== "Button")
                return;
            const nextLabel = labelOf(nextProps);
            if (nextLabel !== labelOf(previousProps))
                native.setText(id, nextLabel);
            const previousOnClick = previousProps.onClick;
            const nextOnClick = nextProps.onClick;
            if (typeof nextOnClick === "function") {
                clicks.set(id, nextOnClick);
                if (typeof previousOnClick !== "function")
                    native.setClickable(id, true);
            }
            else if (typeof previousOnClick === "function") {
                clicks.delete(id);
                native.setClickable(id, false);
            }
        },
        removeChild(parent, child) {
            if (parent === null)
                return;
            native.remove(asDevice(parent).id, asDevice(child).id);
        },
        dispose(instance) {
            const id = asDevice(instance).id;
            clicks.delete(id);
            native.dispose(id);
        },
        replaceRoot(next, _previous) {
            native.loadScreen(next === null ? 0 : asDevice(next).id);
        },
    };
}

});
__tsxDefine("@tsx-lvgl/device/native.js", function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });

});
__tsxDefine("@tsx-lvgl/device/scheduler.js", function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createDeviceScheduler = createDeviceScheduler;
function createDeviceScheduler(timers) {
    const queue = [];
    return {
        enqueue(task) {
            queue.push(task);
        },
        setInterval(task, periodMs) {
            return timers.setInterval(task, periodMs);
        },
        clearInterval(handle) {
            timers.clearInterval(handle);
        },
        drain() {
            if (queue.length === 0)
                return;
            const pending = queue.splice(0, queue.length);
            for (const task of pending) {
                task();
            }
        },
    };
}

});
__tsxDefine("@tsx-lvgl/device/sensors.js", function (require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createNativeMotionSensor = createNativeMotionSensor;
const sensors_1 = require("@tsx-lvgl/sensors");
const DEFAULT_PERIOD_MS = 80;
function toSample(raw, context, sequence) {
    const reading = raw;
    const value = reading.value;
    const hasValidValue = sensors_1.motionSchema.validate(value);
    return {
        sensorId: sensors_1.motionSchema.id,
        schemaVersion: sensors_1.motionSchema.version,
        sequence,
        sampledAtMs: reading.sampledAtMs,
        reloadEpoch: context.reloadEpoch,
        status: reading.status,
        ...(hasValidValue ? { value } : {}),
    };
}
function createNativeMotionSensor(native, timers, periodMs = DEFAULT_PERIOD_MS) {
    let sequence = 0;
    return {
        schema: sensors_1.motionSchema,
        read(context) {
            sequence += 1;
            return Promise.resolve(toSample(native.read(sensors_1.motionSchema.id), context, sequence));
        },
        subscribe(listener, context) {
            const handle = timers.setInterval(() => {
                sequence += 1;
                listener(toSample(native.read(sensors_1.motionSchema.id), context, sequence));
            }, periodMs);
            return () => timers.clearInterval(handle);
        },
    };
}

});
__tsxDefine("@tsx-lvgl/core", function (require, module, exports) {
module.exports = require("@tsx-lvgl/core/index.js");
});
__tsxDefine("@tsx-lvgl/sensors", function (require, module, exports) {
module.exports = require("@tsx-lvgl/sensors/index.js");
});
__tsxDefine("@tsx-lvgl/runtime", function (require, module, exports) {
module.exports = require("@tsx-lvgl/runtime/index.js");
});
__tsxDefine("@tsx-lvgl/device", function (require, module, exports) {
module.exports = require("@tsx-lvgl/device/index.js");
});
__tsxDefine("@tsx-lvgl/core/jsx-runtime", function (require, module, exports) {
module.exports = require("@tsx-lvgl/core/jsx-runtime.js");
});
var __tsxKernel = null;
globalThis.__tsxKernelBoot = function (manifestJson, sourceText) {
  var device = __tsxRequire("@tsx-lvgl/device");
  __tsxKernel = device.createKernel(globalThis.__native);
  var bytes = device.encodeAsciiSource(sourceText);
  if (bytes === null) throw new Error("kernel boot: non-ascii source");
  __tsxKernel.start({ manifest: JSON.parse(manifestJson), source: bytes });
};
globalThis.__tsxKernelReload = function (manifestJson, sourceText) {
  if (__tsxKernel === null) return "rejected kernel-not-started";
  return __tsxKernel.stageReload(manifestJson, sourceText);
};
globalThis.__tsxKernelPump = function () { if (__tsxKernel !== null) __tsxKernel.pump(); };
globalThis.__tsxKernelLastGeneration = function () { return __tsxKernel === null ? 0 : __tsxKernel.lastGeneration(); };
