import { createCapabilityCatalog, createCapabilityToken, issue, selectCapabilityInstance, type BoardDiagnosticsSnapshot, type BoardIssue, type CapabilityBinding, type CapabilityContext, type CapabilityEvent, type CapabilityObserveOptions, type CapabilityRuntime, type CapabilitySchema, type CapabilityState, type CapabilitySubscription } from "@tsx-lvgl/capabilities";
import { motionSchema } from "@tsx-lvgl/sensors";
import { decodeBoardPayload } from "./board-adapter.js";
import type { BoardPlatformAdapter, NativeBoardEvent, NativeCapabilityDescriptor } from "./native.js";

interface Subscriber { readonly id: number; readonly context: CapabilityContext; readonly onState: (binding: CapabilityBinding<unknown>) => void; readonly onEvent?: (event: CapabilityEvent<unknown>) => void; active: boolean; }
interface Producer { readonly descriptor: NativeCapabilityDescriptor; readonly schema: CapabilitySchema<unknown>; readonly subscribers: Map<number, Subscriber>; handle: number; periodMs: number; last?: Reading; }
interface Reading { readonly status: "ready" | "stale" | "unavailable" | "error"; readonly value?: unknown; readonly issue?: BoardIssue; readonly observedAtMs: number; readonly sequence: number; readonly droppedSincePrevious: number; }
const known = new Map([[`${motionSchema.id}@${motionSchema.version}`, motionSchema as CapabilitySchema<unknown>]]);

export class BoardRuntime implements CapabilityRuntime {
  public readonly catalog;
  private readonly descriptors = new Map<string, NativeCapabilityDescriptor[]>();
  private readonly producers = new Map<string, Producer>();
  private readonly handles = new Map<number, Producer>();
  private nextId = 1; private dropped = 0; private queueHighWater = 0; private lastIssue: BoardIssue | undefined; private disposed = false;
  public constructor(private readonly adapter: BoardPlatformAdapter) {
    const registrations: Array<{ token: ReturnType<typeof createCapabilityToken>; instance: { id: string; isDefault: boolean; source: string } }> = [];
    for (const descriptor of adapter.list()) {
      validateDescriptor(descriptor); const schema = known.get(`${descriptor.semanticId}@${descriptor.version}`); if (schema === undefined) continue;
      const entries = this.descriptors.get(schema.id) ?? []; if (entries.some((entry) => entry.instanceId === descriptor.instanceId)) throw new Error(`duplicate native capability descriptor: ${descriptor.instanceId}`);
      entries.push(Object.freeze({ ...descriptor })); this.descriptors.set(schema.id, entries);
      registrations.push({ token: createCapabilityToken({ familyCode: descriptor.familyCode, semanticId: descriptor.semanticId, version: descriptor.version, delivery: descriptor.delivery, validate: schema.validate }), instance: { id: descriptor.instanceId, isDefault: descriptor.isDefault, source: descriptor.source } });
    }
    this.catalog = createCapabilityCatalog(registrations); adapter.setSink((event) => this.handleEvent(event));
  }
  public getBinding<T>(schema: CapabilitySchema<T>, options: CapabilityObserveOptions = {}): CapabilityBinding<T> { const entries = this.descriptors.get(schema.id) ?? []; const instances = entries.map((entry) => ({ id: entry.instanceId, isDefault: entry.isDefault, source: entry.source })); const selected = selectCapabilityInstance(instances, options.instanceId); if (selected.status === "unsupported") return { state: { status: "unsupported", reason: selected.reason }, instances }; if (selected.status === "ambiguous") return { state: selected, instances }; const producer = this.producers.get(selected.instance.id); const cached = producer?.last ?? this.readCached<T>(selected.instance.id, schema); return { state: cached === undefined ? { status: "starting" } : this.asState(cached), instances }; }
  public subscribe<T>(schema: CapabilitySchema<T>, options: CapabilityObserveOptions, context: CapabilityContext, onState: (binding: CapabilityBinding<T>) => void, onEvent?: (event: CapabilityEvent<T>) => void): CapabilitySubscription {
    if (options.enabled === false) return { cancel: () => undefined }; const initial = this.getBinding(schema, options); onState(initial); if (initial.state.status === "unsupported" || initial.state.status === "ambiguous") return { cancel: () => undefined };
    const instanceId = this.selectedInstance(schema, options); if (instanceId === undefined) return { cancel: () => undefined }; let producer = this.producers.get(instanceId); if (producer === undefined) { const descriptor = (this.descriptors.get(schema.id) ?? []).find((entry) => entry.instanceId === instanceId)!; const periodMs = boundPeriod(options.periodMs ?? descriptor.defaultPeriodMs, descriptor); producer = { descriptor, schema, subscribers: new Map(), periodMs, handle: this.adapter.submit({ version: 1, kind: "observe", instanceId, periodMs }) }; this.producers.set(instanceId, producer); this.handles.set(producer.handle, producer); }
    const subscriber: Subscriber = { id: this.nextId++, context, onState: onState as (binding: CapabilityBinding<unknown>) => void, active: true, ...(onEvent === undefined ? {} : { onEvent: onEvent as (event: CapabilityEvent<unknown>) => void }) }; producer.subscribers.set(subscriber.id, subscriber);
    return { cancel: () => { if (!subscriber.active) return; subscriber.active = false; producer!.subscribers.delete(subscriber.id); if (producer!.subscribers.size === 0) { this.adapter.cancel(producer!.handle); this.handles.delete(producer!.handle); this.producers.delete(instanceId); } } };
  }
  public diagnostics(): BoardDiagnosticsSnapshot { const effectivePeriodsMs: Record<string, number> = {}; for (const [id, producer] of this.producers) effectivePeriodsMs[id] = producer.periodMs; return { effectivePeriodsMs, queueDepth: 0, queueHighWater: this.queueHighWater, droppedEvents: this.dropped, activeOwners: [...this.producers.keys()], resourceUse: { observers: this.producers.size }, ...(this.lastIssue === undefined ? {} : { lastIssue: this.lastIssue }) }; }
  public commitEpoch(_epoch: number): void {}
  public rollbackEpoch(_epoch: number): void {}
  public dispose(): void { if (this.disposed) return; this.disposed = true; for (const producer of this.producers.values()) this.adapter.cancel(producer.handle); this.producers.clear(); this.handles.clear(); this.adapter.dispose(); }
  private handleEvent(event: NativeBoardEvent): void { if (this.disposed) return; const producer = this.handles.get(event.handle); if (producer === undefined || !isEventValid(event, producer.descriptor.maxFrameBytes)) return this.reject("board-envelope"); const reading = decodeReading(event, producer.schema); if (reading === undefined) return this.reject("board-reading"); producer.last = reading; if (reading.issue) this.lastIssue = reading.issue; this.queueHighWater = Math.max(this.queueHighWater, producer.subscribers.size); for (const subscriber of producer.subscribers.values()) { if (!subscriber.active || subscriber.context.isCancelled()) continue; const binding = { state: this.asState(reading), instances: [{ id: producer.descriptor.instanceId, isDefault: producer.descriptor.isDefault, source: producer.descriptor.source }] }; subscriber.onState(binding); subscriber.onEvent?.({ semanticId: producer.schema.id, schemaVersion: producer.schema.version, reloadEpoch: subscriber.context.reloadEpoch, status: reading.status === "ready" ? "ok" : reading.status, observedAtMs: reading.observedAtMs, sequence: reading.sequence, droppedSincePrevious: reading.droppedSincePrevious, ...(reading.value === undefined ? {} : { value: reading.value }), ...(reading.issue === undefined ? {} : { issue: reading.issue }) }); } }
  private readCached<T>(instanceId: string, schema: CapabilitySchema<T>): Reading | undefined { const event = this.adapter.readCached(instanceId); return event === undefined || !isEventValid(event, 512) ? undefined : decodeReading(event, schema); }
  private selectedInstance(schema: CapabilitySchema<unknown>, options: CapabilityObserveOptions): string | undefined { const selection = selectCapabilityInstance((this.descriptors.get(schema.id) ?? []).map((entry) => ({ id: entry.instanceId, isDefault: entry.isDefault, source: entry.source })), options.instanceId); return selection.status === "selected" ? selection.instance.id : undefined; }
  private asState<T>(reading: Reading): CapabilityState<T> { return reading.status === "ready" || reading.status === "stale" ? { status: reading.status, value: reading.value as T, observedAtMs: reading.observedAtMs, sequence: reading.sequence, droppedSincePrevious: reading.droppedSincePrevious } : { status: reading.status, issue: reading.issue!, ...(reading.value === undefined ? {} : { last: { value: reading.value as T, observedAtMs: reading.observedAtMs, sequence: reading.sequence, droppedSincePrevious: reading.droppedSincePrevious } }) }; }
  private reject(diagnosticId: string): void { this.dropped += 1; this.lastIssue = issue("protocol-error", "never", diagnosticId); }
}
export function createDefaultBoardDescriptors(): readonly NativeCapabilityDescriptor[] { return Object.freeze([{ familyCode: 0x0101, semanticId: motionSchema.id, instanceId: "motion", version: 1, source: "qmi8658", isDefault: true, delivery: "snapshot", defaultPeriodMs: 80, minPeriodMs: 20, maxPeriodMs: 1000, maxFrameBytes: 512 }]); }
function validateDescriptor(d: NativeCapabilityDescriptor): void { if (!Number.isSafeInteger(d.familyCode) || d.familyCode <= 0 || !d.semanticId || !d.instanceId || !d.source) throw new Error("capability descriptor identity is invalid"); if (d.version !== 1 || d.maxFrameBytes < 1 || d.minPeriodMs < 1 || d.defaultPeriodMs < d.minPeriodMs || d.defaultPeriodMs > d.maxPeriodMs) throw new Error("capability descriptor bounds are invalid"); }
function boundPeriod(requested: number, d: NativeCapabilityDescriptor): number { if (!Number.isSafeInteger(requested) || requested <= 0) return d.defaultPeriodMs; return Math.max(d.minPeriodMs, Math.min(d.maxPeriodMs, requested)); }
function isEventValid(event: NativeBoardEvent, maxFrameBytes: number): boolean { return event.version === 1 && event.kind === "state" && Number.isSafeInteger(event.handle) && Number.isSafeInteger(event.sequence) && event.sequence > 0 && Number.isFinite(event.observedAtMs) && event.payload.length <= maxFrameBytes; }
function decodeReading(event: NativeBoardEvent, schema: CapabilitySchema<unknown>): Reading | undefined { const value = decodeBoardPayload(event.payload); if (value === undefined || (value.status !== "ok" && value.status !== "stale" && value.status !== "unavailable" && value.status !== "error")) return undefined; const dropped = typeof value.droppedSincePrevious === "number" && Number.isSafeInteger(value.droppedSincePrevious) && value.droppedSincePrevious >= 0 ? value.droppedSincePrevious : 0; if ((value.status === "ok" || value.status === "stale") && !schema.validate(value.value)) return undefined; if (value.status === "ok" || value.status === "stale") return { status: value.status === "ok" ? "ready" : "stale", value: value.value, observedAtMs: event.observedAtMs, sequence: event.sequence, droppedSincePrevious: dropped }; const rawIssue = value.issue; if (typeof rawIssue !== "object" || rawIssue === null) return undefined; const candidate = rawIssue as Record<string, unknown>; if (typeof candidate.code !== "string" || typeof candidate.retry !== "string" || typeof candidate.diagnosticId !== "string") return undefined; return { status: value.status, issue: issue(candidate.code as BoardIssue["code"], candidate.retry as BoardIssue["retry"], candidate.diagnosticId), observedAtMs: event.observedAtMs, sequence: event.sequence, droppedSincePrevious: dropped }; }
